### ISSUE TITLE
JSON is out of order

### ISSUE THREAD

**Issue by EricR** [EricR/sys.json#1]
When we call `json.Marshal`, the resulting JSON comes out in a different order (it appears to be sorting by key). We should figure out a way to store this data in something map-like that preserves order.

**Comment by jbreiding** [comment]
Suggestion with regards to this one.

Perhaps answering the question of why the json order matters if the hierarchy is preserved may help here. 

Really I think the question should be does the sorting on the call the json.Marshal affect performance and could it be avoided.

**Comment by EricR** [comment]
@jbreiding I agree. I think we can consider this a non-issue for now since hierarchy is preserved.
